ARG arg_tag_stack

FROM "elastic/stack:${arg_tag_stack}"

# defaults
ARG arg_dir_stack=ELASTIC
ARG arg_dir_log=logs
ARG arg_ver_logstash=logstash-6.3.0
ARG arg_ver_filebeat=filebeat-6.3.0-amd64

ENV DIR_STACK "$arg_dir_stack"
ENV DIR_LOG "$arg_dir_log"
ENV VER_LOGSTASH "$arg_ver_logstash"
ENV VER_FILEBEAT "$arg_ver_filebeat"

WORKDIR /$DIR_STACK

# Logstash
RUN mkdir -p "$DIR_LOG" && \
    wget "https://artifacts.elastic.co/downloads/logstash/${VER_LOGSTASH}.tar.gz" && \
    wget "https://artifacts.elastic.co/downloads/logstash/${VER_LOGSTASH}.tar.gz.sha512" && \
    shasum -a 512 -c "${VER_LOGSTASH}.tar.gz.sha512" && \
    rm -f "${VER_LOGSTASH}.tar.gz.sha512" && \
# the log4j plugin is deprecated -> use Filebeat to collect logs from log4j
# https://www.elastic.co/guide/en/logstash/current/plugins-inputs-log4j.html
# ${VER_LOGSTASH/bin/logstash-plugin install logstash-input-log4j
# install Filebeat
# https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation.html
    wget "https://artifacts.elastic.co/downloads/beats/filebeat/${VER_FILEBEAT}.deb" && \
    dpkg -i "${VER_FILEBEAT}.deb"

COPY ./elk/elk.sh /$DIR_STACK/elk.sh
COPY ./elk/logstash.yml /$DIR_STACK/logstash.yml
COPY ./elk/logstash.conf /$DIR_STACK/logstash.conf
COPY ./elk/pipelines.yml /$DIR_STACK/pipelines.yml
COPY ./elk/filebeat.yml /$DIR_STACK/filebeat.yml

RUN chown -R elasticsearch:elasticsearch /$DIR_STACK

# clean
RUN apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/cache/apt/* && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*  && \
    rm -rf /var/tmp/* && \
    rm -rf /usr/lib/ruby/gems/*/cache/*.gem

# SSH | Kibana | Logstash HTTP | Logstash TCP | Logstash UDP
EXPOSE 22 5601 8888 12345 12345/udp

CMD ["sh", "-c", "/${DIR_STACK}/elk.sh"]
