ARG arg_tag_stack

FROM "elastic/stack:${arg_tag_stack}"

# defaults
ARG arg_dir_stack=ELASTIC

ENV DIR_STACK "$arg_dir_stack"

WORKDIR /$DIR_STACK

# Before Installing Fluentd
# https://docs.fluentd.org/v1.0/articles/before-install
# /etc/sysctl.conf
# must be set on the host OS - otherwise:
# sysctl: setting key "xxx.yyy.zzz": Read-only file system

COPY ./efk/efk.sh /$DIR_STACK/efk.sh

RUN chown -R elasticsearch:elasticsearch /$DIR_STACK

ENV DEBIAN_FRONTEND noninteractive

RUN curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent3.sh | sh && \
    sudo td-agent-gem install fluent-plugin-secure-forward && \
    sudo td-agent-gem install fluent-plugin-elasticsearch

RUN cp -a /etc/td-agent/td-agent.conf /etc/td-agent/td-agent.conf.orig

COPY ./efk/td-agent.conf /etc/td-agent/td-agent.conf

ENV DEBIAN_FRONTEND teletype

# clean
RUN apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/cache/apt/* && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*  && \
    rm -rf /var/tmp/* && \
    rm -rf /usr/lib/ruby/gems/*/cache/*.gem

# SSH | Kibana | Fluentd-HTTP | Fluentd-forward
EXPOSE 22 5601 8888 24224

CMD ["sh", "-c", "/${DIR_STACK}/efk.sh"]
