version: '3'

services:
  base:
    build:
      context: '.'
      dockerfile: 'Dockerfile-Base'
      args:
        arg_ssh_user_pwd: 'root:1234'
        arg_time_zone: 'Europe/Berlin'
        arg_ntp_server_0: '0.de.pool.ntp.org'
        arg_ntp_server_1: '1.de.pool.ntp.org'
    image: "elastic/base:${X_TAG_BASE}"
  stack:
    build:
      context: '.'
      dockerfile: 'Dockerfile-Stack'
      args:
        arg_tag_base: "${X_TAG_BASE}"
        arg_dir_stack: "${X_DIR_STACK}"
        arg_ver_elasticsearch: "${X_VER_ELASTICSEARCH}"
        arg_ver_kibana: "${X_VER_KIBANA}"
    image: "elastic/stack:${X_TAG_STACK}"
  elk:
    build:
      context: '.'
      dockerfile: 'Dockerfile-ELK'
      args:
        arg_tag_stack: "${X_TAG_STACK}"
        arg_dir_stack: "${X_DIR_STACK}"
        arg_dir_log: "${X_DIR_LOG}"
        arg_ver_logstash: "${X_VER_LOGSTASH}"
        arg_ver_filebeat: "${X_VER_FILEBEAT}"
    image: "elastic/elk:${X_TAG_ELK}"
    container_name: 'elk'
    hostname: 'elk'
    ports:
     - '2222:22'
     - "5601:5601"
     - "8888:8888"
     - "12345:12345"
     - "12345:12345/udp"
  efk:
    build:
      context: '.'
      dockerfile: 'Dockerfile-EFK'
      args:
        arg_tag_stack: "${X_TAG_STACK}"
        arg_dir_stack: "${X_DIR_STACK}"
    image: "elastic/efk:${X_TAG_EFK}"
    container_name: 'efk'
    hostname: 'efk'
    ports:
     - '2222:22'
     - "5601:5601"
     - "8888:8888"
     - "24224:24224"
